version: "3.9"
services:
  www:
    build: ./www
    image: yuanchenyang/www
    container_name: www
    volumes:
      - webdav:/usr/local/apache2/webdav
    secrets:
      - webdav_cred
  dashboard:
    build: ./dashboard_app
    image: yuanchenyang/dashboard
    container_name: dashboard
  visualizer:
    build: ./visualizer
    image: yuanchenyang/visualizer
    container_name: visualizer
    healthcheck:
      test: ["CMD-SHELL", "exit 1"]
      interval: 5m
      timeout: 1s
      retries: 1
      start_period: 10s
  archiver:
    build: ./archiver
    image: yuanchenyang/archiver
    container_name: archiver
  pdf:
    build: ./pdf-viewer
    image: yuanchenyang/pdf
    container_name: pdf
volumes:
  webdav:
secrets:
  webdav_cred:
    file: ./secrets/webdav.password
