version: "3.9"
services:
  www:
    build: ./www
    image: yuanchenyang/www
    container_name: www
  dashboard:
    build: ./dashboard_app
    image: yuanchenyang/dashboard
    container_name: dashboard
  visualizer:
    build: ./visualizer
    image: yuanchenyang/visualizer
    container_name: visualizer
  archiver:
    build: ./archiver
    image: yuanchenyang/archiver
    container_name: archiver
  pdf:
    build: ./pdf-viewer
    image: yuanchenyang/pdf
    container_name: pdf
