version: "3.9"
services:
  www:
    build: ./www
    image: yuanchenyang/www
    container_name: www
    expose:
      - "80"
  dashboard:
    build: ./dashboard_app
    image: yuanchenyang/dashboard
    container_name: dashboard
    expose:
      - "80"
  pdf:
    build: ./pdf-viewer
    image: yuanchenyang/pdf
    container_name: pdf
    expose:
      - "80"