services:
  www:
    restart: always
    logging:
      driver: journald
    expose:
      - "80"
  dashboard:
    restart: always
    logging:
      driver: journald
    expose:
      - "80"
    deploy:
      resources:
        limits:
          memory: 300M
  visualizer:
    restart: always
    logging:
      driver: journald
    expose:
      - "80"
  archiver:
    restart: always
    logging:
      driver: journald
    expose:
      - "80"
  pdf:
    restart: always
    logging:
      driver: journald
    expose:
      - "80"
  proxy:
    restart: always
    build: ./proxy
    image: yuanchenyang/proxy
    container_name: proxy
    ports:
      - "80:80"
    logging:
      driver: journald
    depends_on:
      - www
      - dashboard
      - visualizer
      - archiver
      - pdf
