services:
  www:
    restart: unless-stopped
    logging:
      driver: journald
    expose:
      - "80"
  dashboard:
    restart: unless-stopped
    logging:
      driver: journald
    expose:
      - "80"
  visualizer:
    restart: unless-stopped
    logging:
      driver: journald
    expose:
      - "80"
  archiver:
    restart: unless-stopped
    logging:
      driver: journald
    expose:
      - "80"
  pdf:
    restart: unless-stopped
    logging:
      driver: journald
    expose:
      - "80"
  proxy:
    restart: unless-stopped
    build: ./proxy
    image: yuanchenyang/proxy
    container_name: proxy
    ports:
      - "80:80"
    logging:
      driver: journald
