services:
  www:
    restart: unless-stopped
  dashboard:
    restart: unless-stopped
  pdf:
    restart: unless-stopped
  proxy:
    restart: unless-stopped
    build: ./proxy
    image: yuanchenyang/proxy
    container_name: proxy
    ports:
      - "80:80"
